-- StuFit exercise seed data
insert into public.exercises (slug, name, muscle_group, equipment, category, difficulty, technique_md, youtube_url) values
('barbell-bench-press', 'Barbell Bench Press', 'chest', 'barbell', 'weightlifting', 'intermediate', E'## Technique\n- Retract shoulder blades and arch upper back slightly\n- Feet flat on floor, wrists stacked over elbows\n- Lower bar to mid-chest with control\n- Drive feet into floor as you press', 'https://www.youtube.com/watch?v=rT7DgCr-1pg'),
('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', 'dumbbell', 'weightlifting', 'intermediate', E'## Technique\n- Set bench 30-45 degrees\n- Press dumbbells up and slightly together\n- Control the descent to upper chest', 'https://www.youtube.com/watch?v=8iPEnn-ltC8'),
('push-up', 'Push-Up', 'chest', 'bodyweight', 'calisthenics', 'beginner', E'## Technique\n- Hands shoulder-width, body in straight line\n- Lower chest near floor, elbows ~45°\n- Full lockout at top without sagging hips', 'https://www.youtube.com/watch?v=IODxDxX7oi4'),
('dumbbell-fly', 'Dumbbell Fly', 'chest', 'dumbbell', 'weightlifting', 'intermediate', E'## Technique\n- Slight bend in elbows throughout\n- Open arms wide until chest stretch\n- Squeeze chest to bring dumbbells together', null),
('cable-crossover', 'Cable Crossover', 'chest', 'cable', 'weightlifting', 'intermediate', E'## Technique\n- Step forward for stable stance\n- Soft elbow bend, hug motion across body\n- Control return — don''t let weights slam', null),
('overhead-press', 'Overhead Press', 'shoulders', 'barbell', 'weightlifting', 'intermediate', E'## Technique\n- Brace core, glutes tight\n- Bar path close to face\n- Lock out overhead without leaning back excessively', 'https://www.youtube.com/watch?v=2yjwXTZQDDg'),
('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'shoulders', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Neutral or pronated grip at shoulder height\n- Press up without flaring ribs\n- Lower with control to ear level', null),
('lateral-raise', 'Lateral Raise', 'shoulders', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Lead with elbows, slight forward lean\n- Raise to shoulder height, pause briefly\n- Avoid shrugging traps excessively', null),
('face-pull', 'Face Pull', 'shoulders', 'cable', 'weightlifting', 'beginner', E'## Technique\n- Rope at face height, pull to ears\n- Externally rotate at end range\n- Great for rear delts and posture', null),
('tricep-pushdown', 'Tricep Pushdown', 'arms', 'cable', 'weightlifting', 'beginner', E'## Technique\n- Elbows pinned to sides\n- Full extension without shoulder movement\n- Control the eccentric', null),
('skull-crusher', 'Skull Crusher', 'arms', 'barbell', 'weightlifting', 'intermediate', E'## Technique\n- Upper arms vertical and stable\n- Lower bar toward forehead\n- Extend elbows without flaring', null),
('dips', 'Dips', 'chest', 'bodyweight', 'calisthenics', 'intermediate', E'## Technique\n- Lean forward for chest emphasis\n- Lower until upper arms parallel\n- Press up without shoulder pain', null),
('pull-up', 'Pull-Up', 'back', 'bodyweight', 'calisthenics', 'intermediate', E'## Technique\n- Depress scapula before pulling\n- Chest to bar if possible\n- Control descent — no kipping for strength', 'https://www.youtube.com/watch?v=eGo4IYlbE5g'),
('lat-pulldown', 'Lat Pulldown', 'back', 'cable', 'weightlifting', 'beginner', E'## Technique\n- Lean back slightly, chest up\n- Pull bar to upper chest\n- Squeeze lats, avoid behind-neck', null),
('barbell-row', 'Barbell Row', 'back', 'barbell', 'weightlifting', 'intermediate', E'## Technique\n- Hinge hips, neutral spine\n- Pull bar to lower ribs\n- Pause briefly, lower under control', 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ'),
('dumbbell-row', 'Single-Arm Dumbbell Row', 'back', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Support on bench, flat back\n- Pull elbow to hip\n- Don''t rotate torso excessively', null),
('seated-cable-row', 'Seated Cable Row', 'back', 'cable', 'weightlifting', 'beginner', E'## Technique\n- Sit tall, slight knee bend\n- Pull handle to belly button\n- Squeeze shoulder blades together', null),
('deadlift', 'Conventional Deadlift', 'back', 'barbell', 'weightlifting', 'advanced', E'## Technique\n- Bar over mid-foot, lats engaged\n- Push floor away, bar stays close to legs\n- Lock hips and knees together at top', 'https://www.youtube.com/watch?v=op9kVnSso6Q'),
('romanian-deadlift', 'Romanian Deadlift', 'legs', 'barbell', 'weightlifting', 'intermediate', E'## Technique\n- Soft knee bend, hinge at hips\n- Feel hamstring stretch\n- Drive hips forward to stand', 'https://www.youtube.com/watch?v=2SHSKzgLKzY'),
('barbell-squat', 'Barbell Back Squat', 'legs', 'barbell', 'weightlifting', 'intermediate', E'## Technique\n- Bar high or low on traps, brace hard\n- Break at hips and knees together\n- Depth: hip crease below knee if mobile', 'https://www.youtube.com/watch?v=ultWZbUMPL8'),
('goblet-squat', 'Goblet Squat', 'legs', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Hold dumbbell at chest\n- Elbows inside knees at bottom\n- Great for learning squat pattern', null),
('leg-press', 'Leg Press', 'legs', 'machine', 'weightlifting', 'beginner', E'## Technique\n- Feet mid-platform, don''t lock knees hard\n- Lower until ~90° knee bend\n- Press without lifting hips off pad', null),
('leg-extension', 'Leg Extension', 'legs', 'machine', 'weightlifting', 'beginner', E'## Technique\n- Align knee with machine axis\n- Extend fully, control lowering\n- Don''t hyperextend aggressively', null),
('leg-curl', 'Leg Curl', 'legs', 'machine', 'weightlifting', 'beginner', E'## Technique\n- Hips pinned to pad\n- Curl heels to glutes\n- Slow eccentric for hamstrings', null),
('walking-lunge', 'Walking Lunge', 'legs', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Long stride, torso upright\n- Back knee nearly touches floor\n- Drive through front heel', null),
('bulgarian-split-squat', 'Bulgarian Split Squat', 'legs', 'dumbbell', 'weightlifting', 'intermediate', E'## Technique\n- Rear foot elevated, front foot forward\n- Vertical shin, knee tracks toes\n- Control depth for balance', null),
('calf-raise', 'Standing Calf Raise', 'legs', 'machine', 'weightlifting', 'beginner', E'## Technique\n- Full stretch at bottom\n- Pause at top contraction\n- Control tempo — no bouncing', null),
('hip-thrust', 'Barbell Hip Thrust', 'legs', 'barbell', 'weightlifting', 'intermediate', E'## Technique\n- Upper back on bench, chin tucked\n- Drive hips up, squeeze glutes\n- Pause at top, avoid hyperextension', null),
('plank', 'Plank', 'core', 'bodyweight', 'weightlifting', 'beginner', E'## Technique\n- Elbows under shoulders, glutes tight\n- Neutral spine — no sag or pike\n- Breathe steadily', 'https://www.youtube.com/watch?v=ASdvN_XEl_c'),
('hanging-leg-raise', 'Hanging Leg Raise', 'core', 'bodyweight', 'weightlifting', 'intermediate', E'## Technique\n- Minimize swinging\n- Curl pelvis up, not just legs\n- Control descent', null),
('cable-crunch', 'Cable Crunch', 'core', 'cable', 'weightlifting', 'beginner', E'## Technique\n- Hips fixed, round upper back\n- Pull rope toward thighs\n- Feel abs, not hip flexors', null),
('russian-twist', 'Russian Twist', 'core', 'bodyweight', 'weightlifting', 'beginner', E'## Technique\n- Lean back slightly, feet optional anchor\n- Rotate through thoracic spine\n- Add weight when form is solid', null),
('barbell-curl', 'Barbell Curl', 'arms', 'barbell', 'weightlifting', 'beginner', E'## Technique\n- Elbows at sides, no swing\n- Full supination at top\n- Lower under control', null),
('hammer-curl', 'Hammer Curl', 'arms', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Neutral grip throughout\n- Alternating or simultaneous\n- Avoid rocking torso', null),
('chin-up', 'Chin-Up', 'back', 'bodyweight', 'calisthenics', 'intermediate', E'## Technique\n- Supinated grip, shoulder-width\n- Pull chest to bar\n- Great bicep and lat builder', null),
('inverted-row', 'Inverted Row', 'back', 'bodyweight', 'calisthenics', 'beginner', E'## Technique\n- Body straight under bar\n- Pull chest to bar\n- Scale angle for difficulty', null),
('pike-push-up', 'Pike Push-Up', 'shoulders', 'bodyweight', 'calisthenics', 'intermediate', E'## Technique\n- Hips high, head toward floor\n- Vertical pressing pattern\n- Progress toward handstand push-up', null),
('dumbbell-pullover', 'Dumbbell Pullover', 'chest', 'dumbbell', 'weightlifting', 'intermediate', E'## Technique\n- Slight bend elbows, arc motion\n- Stretch lats and chest at bottom\n- Keep hips stable on bench', null),
('front-squat', 'Front Squat', 'legs', 'barbell', 'weightlifting', 'advanced', E'## Technique\n- Elbows high, bar on front delts\n- Torso more upright than back squat\n- Core bracing critical', null),
('sumo-deadlift', 'Sumo Deadlift', 'legs', 'barbell', 'weightlifting', 'advanced', E'## Technique\n- Wide stance, toes out\n- Hands inside knees\n- Push floor, chest up', null),
('farmers-walk', 'Farmer''s Walk', 'full_body', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Tall posture, shoulders packed\n- Short quick steps\n- Grip and core challenge', null),
('kettlebell-swing', 'Kettlebell Swing', 'full_body', 'kettlebell', 'cardio', 'intermediate', E'## Technique\n- Hinge not squat\n- Snap hips, arms relaxed\n- Bell to chest height for conditioning', null),
('box-jump', 'Box Jump', 'legs', 'bodyweight', 'plyometrics', 'intermediate', E'## Technique\n- Soft landing on box\n- Step down for recovery sets\n- Full hip extension at top', null),
('battle-rope', 'Battle Rope Waves', 'full_body', 'rope', 'cardio', 'beginner', E'## Technique\n- Athletic stance, core braced\n- Alternating or simultaneous waves\n- Steady breathing', null),
('db-bench-press', 'Dumbbell Bench Press', 'chest', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Neutral wrist, 45° elbow path\n- Touch dumbbells at chest level\n- Press without clanking weights', null),
('db-incline-press', 'Incline DB Press', 'chest', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- 30° incline for upper chest\n- Control ROM\n- Home-friendly push movement', null),
('db-shrug', 'Dumbbell Shrug', 'back', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Straight up shrug, no rolling\n- Pause at top\n- Lower slowly', null),
('glute-bridge', 'Glute Bridge', 'legs', 'bodyweight', 'weightlifting', 'beginner', E'## Technique\n- Heels close to glutes\n- Drive hips up, squeeze 2 sec\n- No lumbar overextension', null),
('reverse-lunge', 'Reverse Lunge', 'legs', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Step back, front shin vertical\n- Torso upright\n- Push through front foot to stand', null),
('side-plank', 'Side Plank', 'core', 'bodyweight', 'weightlifting', 'beginner', E'## Technique\n- Elbow under shoulder, hips high\n- Straight line head to feet\n- Hold without rotating', null),
('mountain-climber', 'Mountain Climbers', 'core', 'bodyweight', 'cardio', 'beginner', E'## Technique\n- High plank, drive knees fast\n- Hips level\n- Use for conditioning finishers', null),
('burpee', 'Burpee', 'full_body', 'bodyweight', 'plyometrics', 'intermediate', E'## Technique\n- Chest to floor on descent\n- Explosive stand and optional jump\n- Pace for conditioning', null),
('jump-rope', 'Jump Rope', 'full_body', 'bodyweight', 'cardio', 'beginner', E'## Technique\n- Light on balls of feet\n- Small jumps, wrists rotate rope\n- Great warm-up', null),
('band-pull-apart', 'Band Pull-Apart', 'shoulders', 'band', 'weightlifting', 'beginner', E'## Technique\n- Arms straight, pull band to chest\n- Squeeze rear delts\n- High reps for shoulder health', null),
('wall-sit', 'Wall Sit', 'legs', 'bodyweight', 'weightlifting', 'beginner', E'## Technique\n- Back flat on wall, thighs parallel\n- Knees over ankles\n- Breathe, hold time', null),
('step-up', 'Step-Up', 'legs', 'dumbbell', 'weightlifting', 'beginner', E'## Technique\n- Full foot on box\n- Drive through working leg only\n- Don''t push off back foot', null),
('good-morning', 'Good Morning', 'legs', 'barbell', 'weightlifting', 'advanced', E'## Technique\n- Bar on back like squat\n- Hinge hips, soft knees\n- Light weight until mastered', null),
('arnold-press', 'Arnold Press', 'shoulders', 'dumbbell', 'weightlifting', 'intermediate', E'## Technique\n- Rotate palms during press\n- Full ROM shoulder builder\n- Control weight', null),
('muscle-up', 'Muscle-Up', 'back', 'bodyweight', 'calisthenics', 'advanced', E'## Technique\n- Explosive pull with false grip transition\n- Keep rings/bar close\n- Progress with negatives and band assist', null),
('handstand-hold', 'Handstand Hold', 'shoulders', 'bodyweight', 'calisthenics', 'advanced', E'## Technique\n- Stack wrists, shoulders, hips\n- Brace core, breathe\n- Use wall for balance when learning', null),
('l-sit', 'L-Sit', 'core', 'bodyweight', 'calisthenics', 'intermediate', E'## Technique\n- Depress shoulders, legs parallel to floor\n- Point toes, hold steady\n- Scale on parallettes or floor', null),
('pistol-squat', 'Pistol Squat', 'legs', 'bodyweight', 'calisthenics', 'advanced', E'## Technique\n- One leg extended, slow descent\n- Keep heel down if possible\n- Use support until strong', null),
('rowing-machine', 'Rowing Machine', 'full_body', 'machine', 'cardio', 'beginner', E'## Technique\n- Drive with legs first, then lean, then pull\n- Reverse sequence on recovery\n- Steady stroke rate for intervals', null),
('bike-intervals', 'Bike Intervals', 'legs', 'machine', 'cardio', 'beginner', E'## Technique\n- Warm up 5 min\n- Hard effort intervals with easy recovery\n- Keep cadence smooth', null),
('treadmill-run', 'Treadmill Run', 'legs', 'machine', 'cardio', 'beginner', E'## Technique\n- Upright posture, midfoot strike\n- Start easy, build pace gradually\n- Use incline for variety', null),
('assault-bike', 'Assault Bike', 'full_body', 'machine', 'cardio', 'intermediate', E'## Technique\n- Push and pull handles with legs\n- High output for short bursts\n- Control breathing', null),
('broad-jump', 'Broad Jump', 'legs', 'bodyweight', 'plyometrics', 'intermediate', E'## Technique\n- Swing arms, hinge and explode forward\n- Stick landing with soft knees\n- Walk back between reps', null),
('squat-jump', 'Squat Jump', 'legs', 'bodyweight', 'plyometrics', 'intermediate', E'## Technique\n- Quarter squat load, jump vertically\n- Land quietly, reset each rep\n- Quality over max height when fatigued', null),
('lateral-bound', 'Lateral Bound', 'legs', 'bodyweight', 'plyometrics', 'intermediate', E'## Technique\n- Push off one leg, land on the other\n- Stick landing 1–2 seconds\n- Stay low and athletic', null),
('tuck-jump', 'Tuck Jump', 'legs', 'bodyweight', 'plyometrics', 'intermediate', E'## Technique\n- Explosive vertical jump, knees to chest\n- Land softly with knees bent\n- Low rep sets for power', null),
('hamstring-stretch', 'Hamstring Stretch', 'legs', 'bodyweight', 'stretching', 'beginner', E'## Technique\n- Hinge at hips, flat back\n- Hold 30–45 seconds per side\n- No bouncing', null),
('hip-flexor-stretch', 'Hip Flexor Stretch', 'legs', 'bodyweight', 'stretching', 'beginner', E'## Technique\n- Half-kneeling, tuck pelvis\n- Lean forward gently\n- Hold 30–45 seconds', null),
('pigeon-pose', 'Pigeon Pose', 'legs', 'bodyweight', 'stretching', 'beginner', E'## Technique\n- Front shin angled, back leg extended\n- Square hips, fold forward if comfortable\n- Hold 45–60 seconds', null),
('cat-cow', 'Cat-Cow', 'back', 'bodyweight', 'stretching', 'beginner', E'## Technique\n- Alternate spinal flexion and extension\n- Move with breath\n- 8–12 slow cycles', null),
('shoulder-dislocates', 'Shoulder Dislocates', 'shoulders', 'band', 'stretching', 'beginner', E'## Technique\n- Wide grip on band or PVC\n- Pass overhead with straight arms\n- Control range, no pain', null)
on conflict (slug) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  category = excluded.category,
  difficulty = excluded.difficulty,
  technique_md = excluded.technique_md,
  youtube_url = excluded.youtube_url;
